version: "3.8"

services:
  pcc0cc08080cg0go0kwokkw8-183647054648:
    build: .
    container_name: pcc0cc08080cg0go0kwokkw8-183647054648
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    networks:
      - app-network
    expose:
      - "PORT"

  ollama:
    image: ollama/ollama
    container_name: ollama
    expose:
      - "11434"
    ports:
      - "11434:11434"
    networks:
      - app-network

networks:
  coolify:
    external: true
