version: "3.8"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    my-app:
      build: .
      extra_hosts:
        - "host.docker.internal:host-gateway"
  
  nextjs-app:
    container_name: nextjs-app
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama
    network_mode: "host"
volumes:
  ollama_data: