version: "3.8"
services:
  my-service:
  build: .
  container_name: pcc0cc08080cg0go0kwokkw8
  environment:
    - OLLAMA_URL=http://ollama_container:11434 # Use container name for communication
  networks:
    - my_network

ollama_container:
  ollama:
  image: ollama/ollama
  container_name: ollama_container
  ports:
    - "11434:11434"
  volumes:
    - ollama-data:/root/.ollama
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:11434"]
    interval: 10s
    timeout: 5s
    retries: 5
  networks:
    - my_network # This ensures that your Ollama container is on the same network as your Node.js app

networks:
  my_network:
    driver: bridge
