networks:
  my_network:
    driver: bridge

services:
  ollama:
    container_name: j8okgsso4wkoc04so004k8ws
    image: j8okgsso4wkoc04so004k8ws:62a83d5029b2011d32c33927d5b41eddb0a5d02f
    networks:
      - my_network

  my-service:
    build: .
    container_name: pcc0cc08080cg0go0kwokkw8
    environment:
      - OLLAMA_URL=http://j8okgsso4wkoc04so004k8ws:11434 # Use container name for communication
    networks:
      - my_network
