version: '3.8'
services:
  my-nextjs-app:
    build: .
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - mynetwork

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge