services:
  my-service:
    build: .
    container_name: my-container
    restart: unless-stopped
    network_mode: "host"
    environment:
    - OLLAMA_URL=http://host.docker.internal:11434
    networks:
      - coolify
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  coolify:
    external: true
