services:
  my-service:
    build: .
    container_name: pcc0cc08080cg0go0kwokkw8
    restart: unless-stopped
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    networks:
      - coolify
