services:
  my-service:
    build: .
    container_name: pcc0cc08080cg0go0kwokkw8
    restart: unless-stopped
    network_mode: "host" # Share host network stack
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_URL=http://10.0.1.10:11434

    ports:
      - "8000:8000"
      - "11434:11434" # Expose port for Ollama

    networks:
      - coolify

networks:
  coolify:
    external: true
