version: "3.8"

services:
  nextjs-app:
    build: .
    container_name: nextjs-app
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    networks:
      - app-network
    expose:
      - "PORT"

  ollama:
    image: ollama/ollama
    container_name: ollama
    expose:
      - "11434"
    ports:
      - "11434:11434"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
