services:
  my-service:
    build: .
    container_name: my-container
    restart: unless-stopped
    network_mode: "host"
    environment:
      - OLLAMA_URL=http://127.0.0.1:11434
    networks:
      - coolify

networks:
  coolify:
    external: true
