services:
  my-service:
    build: .
    container_name: pcc0cc08080cg0go0kwokkw8
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:31.187.72.255"
    environment:
      - OLLAMA_URL=http://31.187.72.255:11434
    ports:
      - "8000:8000"
      - "11434:11434" # Expose port for Ollama

    networks:
      - coolify

networks:
  coolify:
    external: true
